### ISSUE TITLE
I found some GitHub Repos that may be of interest

### ISSUE THREAD

**Issue by SpaghettiCat0** [zurgeg/echovr-custom#5]
https://github.com/Skinny229/Project-Astrea
https://github.com/ArgosVR/CommunityCommunityKit
https://github.com/Ajedi32/echovr-api

**Comment by TimosCodd** [comment]
good find!

**Comment by zurgeg** [comment]
> https://github.com/Skinny229/Project-Astrea https://github.com/ArgosVR/CommunityCommunityKit https://github.com/Ajedi32/echovr-api

Gotcha.
